export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
export const FETCH_USER_DATA_PENDING = "FETCH_USER_DATA_PENDING";
export const FETCH_USER_DATA_ERROR = "FETCH_USER_DATA_ERROR";

export const MOVIES_ID_DETAIL_SUCCESS = "MOVIES_ID_DETAIL_SUCCESS";
export const MOVIES_ID_DETAIL_PENDING = "MOVIES_ID_DETAIL_PENDING";
export const MOVIES_ID_DETAIL_ERROR = "MOVIES_ID_DETAIL_ERROR";

export const MOVIES_CAST_CREW_DETAIL_SUCCESS = "MOVIES_CAST_CREW_DETAIL_SUCCESS";
export const MOVIES_CAST_CREW_DETAIL_PENDING = "MOVIES_CAST_CREW_DETAIL_PENDING";
export const MOVIES_CAST_CREW_DETAIL_ERROR = "MOVIES_CAST_CREW_DETAIL_ERROR";

export const MOVIES_BUDGET_REVENUE_DETAIL_SUCCESS = "MOVIES_BUDGET_REVENUE_DETAIL_SUCCESS";
export const MOVIES_BUDGET_REVENUE_DETAIL_PENDING = "MOVIES_BUDGET_REVENUE_DETAIL_PENDING";
export const MOVIES_BUDGET_REVENUE_DETAIL_ERROR = "MOVIES_BUDGET_REVENUE_DETAIL_ERROR";

export const MOVIES_KEYWORDS_DETAIL_SUCCESS = "MOVIES_KEYWORDS_DETAIL_SUCCESS";
export const MOVIES_KEYWORDS_DETAIL_PENDING = "MOVIES_KEYWORDS_DETAIL_PENDING";
export const MOVIES_KEYWORDS_DETAIL_ERROR = "MOVIES_KEYWORDS_DETAIL_ERROR";

export const MOVIES_REVIEWS_DETAIL_SUCCESS = "MOVIES_REVIEWS_DETAIL_SUCCESS";
export const MOVIES_REVIEWS_DETAIL_PENDING = "MOVIES_REVIEWS_DETAIL_PENDING";
export const MOVIES_REVIEWS_DETAIL_ERROR = "MOVIES_REVIEWS_DETAIL_ERROR";